#############################################################################
# Makefile for building: google_maps
# Generated by qmake (2.01a) (Qt 4.6.3) on: Tue Oct 5 08:48:16 2010
# Project:  google_maps.pro
# Template: app
# Command: /home/skander/qtsdk-2010.04/qt/bin/qmake -unix -o Makefile google_maps.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../qtsdk-2010.04/qt/mkspecs/linux-g++ -I. -I../../qtsdk-2010.04/qt/include/QtCore -I../../qtsdk-2010.04/qt/include/QtGui -I../../qtsdk-2010.04/qt/include/QtWebKit -I../../qtsdk-2010.04/qt/include -Ibuild -Ibuild
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/skander/qtsdk-2010.04/qt/lib
LIBS          = $(SUBLIBS)  -L/home/skander/qtsdk-2010.04/qt/lib -lQtWebKit -L/home/skander/qtsdk-2010.04/qt/lib -L/usr/X11R6/lib -lphonon -L/home/berlin/dev/qt-4.6.3-opensource-shipping/this_path_is_supposed_to_be_very_long_hopefully_this_is_long_enough/qt/lib -lQtDBus -lQtXml -lQtXmlPatterns -lQtNetwork -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/skander/qtsdk-2010.04/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/google_maps.cpp \
		src/main.cpp build/moc_google_maps.cpp
OBJECTS       = build/google_maps.o \
		build/main.o \
		build/moc_google_maps.o
DIST          = ../../qtsdk-2010.04/qt/mkspecs/common/g++.conf \
		../../qtsdk-2010.04/qt/mkspecs/common/unix.conf \
		../../qtsdk-2010.04/qt/mkspecs/common/linux.conf \
		../../qtsdk-2010.04/qt/mkspecs/qconfig.pri \
		../../qtsdk-2010.04/qt/mkspecs/features/qt_functions.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/qt_config.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/exclusive_builds.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/default_pre.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/release.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/default_post.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/warn_on.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/qt.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/unix/thread.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/moc.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/resources.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/uic.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/yacc.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/lex.prf \
		google_maps.pro
QMAKE_TARGET  = google_maps
DESTDIR       = 
TARGET        = google_maps

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): build/ui_google_maps.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: google_maps.pro  ../../qtsdk-2010.04/qt/mkspecs/linux-g++/qmake.conf ../../qtsdk-2010.04/qt/mkspecs/common/g++.conf \
		../../qtsdk-2010.04/qt/mkspecs/common/unix.conf \
		../../qtsdk-2010.04/qt/mkspecs/common/linux.conf \
		../../qtsdk-2010.04/qt/mkspecs/qconfig.pri \
		../../qtsdk-2010.04/qt/mkspecs/features/qt_functions.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/qt_config.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/exclusive_builds.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/default_pre.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/release.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/default_post.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/warn_on.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/qt.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/unix/thread.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/moc.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/resources.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/uic.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/yacc.prf \
		../../qtsdk-2010.04/qt/mkspecs/features/lex.prf \
		/home/skander/qtsdk-2010.04/qt/lib/libQtWebKit.prl \
		/home/skander/qtsdk-2010.04/qt/lib/libphonon.prl \
		/home/skander/qtsdk-2010.04/qt/lib/libQtDBus.prl \
		/home/skander/qtsdk-2010.04/qt/lib/libQtXml.prl \
		/home/skander/qtsdk-2010.04/qt/lib/libQtCore.prl \
		/home/skander/qtsdk-2010.04/qt/lib/libQtGui.prl \
		/home/skander/qtsdk-2010.04/qt/lib/libQtXmlPatterns.prl \
		/home/skander/qtsdk-2010.04/qt/lib/libQtNetwork.prl
	$(QMAKE) -unix -o Makefile google_maps.pro
../../qtsdk-2010.04/qt/mkspecs/common/g++.conf:
../../qtsdk-2010.04/qt/mkspecs/common/unix.conf:
../../qtsdk-2010.04/qt/mkspecs/common/linux.conf:
../../qtsdk-2010.04/qt/mkspecs/qconfig.pri:
../../qtsdk-2010.04/qt/mkspecs/features/qt_functions.prf:
../../qtsdk-2010.04/qt/mkspecs/features/qt_config.prf:
../../qtsdk-2010.04/qt/mkspecs/features/exclusive_builds.prf:
../../qtsdk-2010.04/qt/mkspecs/features/default_pre.prf:
../../qtsdk-2010.04/qt/mkspecs/features/release.prf:
../../qtsdk-2010.04/qt/mkspecs/features/default_post.prf:
../../qtsdk-2010.04/qt/mkspecs/features/warn_on.prf:
../../qtsdk-2010.04/qt/mkspecs/features/qt.prf:
../../qtsdk-2010.04/qt/mkspecs/features/unix/thread.prf:
../../qtsdk-2010.04/qt/mkspecs/features/moc.prf:
../../qtsdk-2010.04/qt/mkspecs/features/resources.prf:
../../qtsdk-2010.04/qt/mkspecs/features/uic.prf:
../../qtsdk-2010.04/qt/mkspecs/features/yacc.prf:
../../qtsdk-2010.04/qt/mkspecs/features/lex.prf:
/home/skander/qtsdk-2010.04/qt/lib/libQtWebKit.prl:
/home/skander/qtsdk-2010.04/qt/lib/libphonon.prl:
/home/skander/qtsdk-2010.04/qt/lib/libQtDBus.prl:
/home/skander/qtsdk-2010.04/qt/lib/libQtXml.prl:
/home/skander/qtsdk-2010.04/qt/lib/libQtCore.prl:
/home/skander/qtsdk-2010.04/qt/lib/libQtGui.prl:
/home/skander/qtsdk-2010.04/qt/lib/libQtXmlPatterns.prl:
/home/skander/qtsdk-2010.04/qt/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile google_maps.pro

dist: 
	@$(CHK_DIR_EXISTS) build/google_maps1.0.0 || $(MKDIR) build/google_maps1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/google_maps1.0.0/ && $(COPY_FILE) --parents src/google_maps.h build/google_maps1.0.0/ && $(COPY_FILE) --parents src/google_maps.cpp src/main.cpp build/google_maps1.0.0/ && $(COPY_FILE) --parents ui/google_maps.ui build/google_maps1.0.0/ && (cd `dirname build/google_maps1.0.0` && $(TAR) google_maps1.0.0.tar google_maps1.0.0 && $(COMPRESS) google_maps1.0.0.tar) && $(MOVE) `dirname build/google_maps1.0.0`/google_maps1.0.0.tar.gz . && $(DEL_FILE) -r build/google_maps1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc_google_maps.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_google_maps.cpp
build/moc_google_maps.cpp: build/ui_google_maps.h \
		src/google_maps.h
	/home/skander/qtsdk-2010.04/qt/bin/moc $(DEFINES) $(INCPATH) src/google_maps.h -o build/moc_google_maps.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/ui_google_maps.h
compiler_uic_clean:
	-$(DEL_FILE) build/ui_google_maps.h
build/ui_google_maps.h: ui/google_maps.ui
	/home/skander/qtsdk-2010.04/qt/bin/uic ui/google_maps.ui -o build/ui_google_maps.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/google_maps.o: src/google_maps.cpp src/google_maps.h \
		build/ui_google_maps.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/google_maps.o src/google_maps.cpp

build/main.o: src/main.cpp src/google_maps.h \
		build/ui_google_maps.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/moc_google_maps.o: build/moc_google_maps.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_google_maps.o build/moc_google_maps.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

